/** Loading of precomputed piece silhouette templates.
 *  Templates are generated by scripts/gen-templates.mjs from open-source SVG
 *  piece sets (see assets/pieces/LICENSES.md) and bundled as JSON. */

import type { PieceType } from './types';
import templatesJson from './templates.gen.json';

export interface PieceTemplate {
  set: string;
  piece: PieceType;
  color: 'w' | 'b';
  grid: Float32Array;
  relHeight: number;
  relWidth: number;
}

interface RawTemplateFile {
  size: number;
  templates: {
    set: string;
    piece: string;
    color: string;
    grid: string; // base64 uint8
    relHeight: number;
    relWidth: number;
  }[];
}

function base64ToBytes(b64: string): Uint8Array {
  if (typeof atob === 'function') {
    const bin = atob(b64);
    const out = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
    return out;
  }
  // Node (tests)
  return new Uint8Array(Buffer.from(b64, 'base64'));
}

let cache: PieceTemplate[] | null = null;

export function loadTemplates(): PieceTemplate[] {
  if (cache) return cache;
  const raw = templatesJson as unknown as RawTemplateFile;
  cache = raw.templates.map((t) => {
    const bytes = base64ToBytes(t.grid);
    const grid = new Float32Array(bytes.length);
    for (let i = 0; i < bytes.length; i++) grid[i] = bytes[i] / 255;
    return {
      set: t.set,
      piece: t.piece as PieceType,
      color: t.color as 'w' | 'b',
      grid,
      relHeight: t.relHeight,
      relWidth: t.relWidth,
    };
  });
  return cache;
}
